<?php
/*
 * File generated by ModulesGarden packages system
 * 
 * Below you can find current version & revision of this module
 */

$moduleVersion = '1.6.0';
$moduleRevision = '1af3ceadbec6685dde66e9a6de442f71f2e82232';
$moduleWikiUrl = 'http://www.docs.modulesgarden.com/Virtuozzo_For_WHMCS';